// ------------------------------------------------------------------------------------------------------------------------
// SysSettings
// ------------------------------------------------------------------------------------------------------------------------

Core.Configuration.SysSettings.SetDefValue(userConnection, "ScShipmentManualIntegrationDate", Get<DateTime>("AutoGeneratedPageUserTask1.StartDate"));
